name: Format and Upload Script

on:
  push:
    branches:
      - main  # 触发条件：推送到 main 分支

jobs:
  format-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install shfmt for formatting
      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt

      # Format the input.sh file
      - name: Format the script
        run: |
          shfmt -w input.sh  # 格式化 input.sh 文件

      # Upload the formatted input.sh as an artifact
      - name: Upload formatted script as artifact
        uses: actions/upload-artifact@v2  # 使用正确的版本
        with:
          name: formatted-script  # artifact 名称
          path: input.sh          # 上传的文件路径
